version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - unified-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: unifiedtransform
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_PASSWORD: secret
      MYSQL_USER: unifiedtransform
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - unified-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - unified-network

networks:
  unified-network:
    driver: bridge

volumes:
  dbdata: